// All pixel sprites as character grids ('.' = transparent, legend in
// palette.ts). Hand-authored, code-reviewable, no binary assets.
// Plant sprites: 16×16, four growth stages — stage 0 is a shared seedling,
// stages 1–3 are per plant and keyed `<plantId>-<stage>`.

export type SpriteGrid = string[]

const seedling: SpriteGrid = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '......l.l.......',
  '.....lFlFl......',
  '......LfL.......',
  '.......f........',
  '.......f........',
  '.......G........',
  '................',
  '................',
  '................',
]

const basilikum1: SpriteGrid = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '......ll........',
  '.....lFFl.......',
  '....lFfFFl......',
  '.....FfGF.......',
  '......Gf........',
  '.......f........',
  '.......G........',
  '................',
  '................',
  '................',
]

const basilikum2: SpriteGrid = [
  '................',
  '................',
  '................',
  '.....ll.l.......',
  '....lFFlFl......',
  '...lFfFFfFl.....',
  '...lFfffFFl.....',
  '....FfGGfF......',
  '...lFfGGfFl.....',
  '....lFffFl......',
  '.....GffG.......',
  '......ff........',
  '.......G........',
  '................',
  '................',
  '................',
]

const basilikum3: SpriteGrid = [
  '................',
  '....l.L.l.......',
  '...lLlLlLl......',
  '..lFLFFLFFl.....',
  '..LfFffFfFL.....',
  '.lFfffffffFl....',
  '.lFfGfffGfFl....',
  '..FfGGfGGfF.....',
  '.lFfGfffGfFl....',
  '..lLFfffFLl.....',
  '...lFfffFl......',
  '....GfffG.......',
  '.....fGf........',
  '......G.........',
  '................',
  '................',
]

const minze1: SpriteGrid = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '......L.........',
  '.....lF.L.......',
  '.....Fl.Fl......',
  '......FlF.......',
  '......fFf.......',
  '.......f........',
  '.......f........',
  '.......G........',
  '................',
  '................',
  '................',
]

const minze2: SpriteGrid = [
  '................',
  '................',
  '....L...L.......',
  '....Fl.lF.......',
  '....lF.Fl.......',
  '.....FlF........',
  '..L..fFf..L.....',
  '..Fl.lfl.lF.....',
  '...Fl.f.lF......',
  '....FlflF.......',
  '.....fGf........',
  '......f.........',
  '......G.........',
  '................',
  '................',
  '................',
]

const minze3: SpriteGrid = [
  '.....M.M........',
  '....LMLML.......',
  '....lF.Fl.......',
  '...LF...FL......',
  '...lF.L.Fl......',
  '....FlFlF.......',
  '..L.lfFfl.L.....',
  '..Fl.lfl.lF.....',
  '..lFl.f.lFl.....',
  '...lFlflFl......',
  '....lfGfl.......',
  '.....fGf........',
  '......f.........',
  '......G.........',
  '................',
  '................',
]

const lavendel1: SpriteGrid = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '......l.........',
  '....l.F.l.......',
  '....F.f.F.......',
  '.....fff........',
  '......f.........',
  '......G.........',
  '................',
  '................',
  '................',
]

const lavendel2: SpriteGrid = [
  '................',
  '................',
  '................',
  '......m.........',
  '..m...P...m.....',
  '..P...P...P.....',
  '..f...f...f.....',
  '..f.l.f.l.f.....',
  '...flf.flf......',
  '....ff.ff.......',
  '.....fff........',
  '......f.........',
  '......G.........',
  '................',
  '................',
  '................',
]

const lavendel3: SpriteGrid = [
  '..M...M...M.....',
  '..m.M.m.M.m.....',
  '..P.m.P.m.P.....',
  '..m.P.m.P.m.....',
  '..P.m.P.m.P.....',
  '..f.P.f.P.f.....',
  '..f.f.f.f.f.....',
  '..fl..f..lf.....',
  '..Fl..f..lF.....',
  '...flffflf......',
  '....ff.ff.......',
  '.....fff........',
  '......f.........',
  '......G.........',
  '................',
  '................',
]

const karotte1: SpriteGrid = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '......l.l.......',
  '.....F.l.F......',
  '......FlF.......',
  '.......f........',
  '.......f........',
  '......RR........',
  '................',
  '................',
  '................',
]

const karotte2: SpriteGrid = [
  '................',
  '................',
  '................',
  '......l.l.......',
  '....l.F.F.l.....',
  '.....FlFlF......',
  '......fff.......',
  '.......f........',
  '.......f........',
  '......RRR.......',
  '......RRR.......',
  '.......R........',
  '................',
  '................',
  '................',
  '................',
]

const karotte3: SpriteGrid = [
  '................',
  '....l..l..l.....',
  '....Fl.F.lF.....',
  '.....lFlFl......',
  '....FlFFFlF.....',
  '.....fFfFf......',
  '......fff.......',
  '.....RRRRR......',
  '.....ORRRR......',
  '......RRR.......',
  '......RRR.......',
  '.......R........',
  '................',
  '................',
  '................',
  '................',
]

const tomate1: SpriteGrid = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '......l.........',
  '.....lF.l.......',
  '......FlF.......',
  '.....l.f........',
  '......FfL.......',
  '.......f........',
  '.......f........',
  '.......G........',
  '................',
  '................',
  '................',
]

const tomate2: SpriteGrid = [
  '................',
  '................',
  '.....ll.l.......',
  '....lFFlFl......',
  '...lFfFFfFl.....',
  '...lFLLfFFl.....',
  '....FfffFl......',
  '...lFfLLfFl.....',
  '....lFffFl......',
  '.....GffG.......',
  '......ff........',
  '.......G........',
  '................',
  '................',
  '................',
  '................',
]

const tomate3: SpriteGrid = [
  '................',
  '.....ll.l.......',
  '....lFFlFl......',
  '...lFfFFfFl.....',
  '..lFfRRfFFl.....',
  '..lFfRrfRRl.....',
  '...FffffRrl.....',
  '..lFRRfFfFl.....',
  '...lFRrfFl......',
  '.....GffG.......',
  '......ff........',
  '.......G........',
  '................',
  '................',
  '................',
  '................',
]

const kuerbis1: SpriteGrid = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '......l.l.......',
  '...f..lf........',
  '....ff.f...GG...',
  '......ff...GG...',
  '................',
  '................',
  '................',
]

const kuerbis2: SpriteGrid = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '........G.......',
  '.....l..G.l.....',
  '.....gGGGGg.....',
  '....gGGGGGGg....',
  '....gGGOGGGg....',
  '.....gGGGGg.....',
  '................',
  '................',
  '................',
]

const kuerbis3: SpriteGrid = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '.......GG.......',
  '....l..GG..l....',
  '....oOOOOOOo....',
  '...oOyOOoOOOo...',
  '..oOyOOOoOOOOo..',
  '..oOOOOOoOOOOo..',
  '..oOOOOOoOOOOo..',
  '...oOOOOoOOOo...',
  '....oooooooo....',
  '................',
  '................',
]

/** Raised-bed soil tile (one plot). */
const soil: SpriteGrid = [
  'kkkkkkkkkkkkkkkk',
  'kbbbbbbbbbbbbbbk',
  'kDddddddddddddDk',
  'kDdkddddkdddddDk',
  'kDddddddddddddDk',
  'kDdddkddDddddkDk',
  'kDdDdddddddddkDk',
  'kDddddddkddddddk',
  'kDdddDdddddDddDk',
  'kDdkddddddddddDk',
  'kDddddddDdddkdDk',
  'kDdddkddddddddDk',
  'kDdDddddddkdddDk',
  'kDddddddddddddDk',
  'kDDDDDDDDDDDDDDk',
  'kkkkkkkkkkkkkkkk',
]

/** Dashed "buy a plot" ghost tile. */
const ghostPlot: SpriteGrid = [
  'nn..nn..nn..nn..',
  'n..............n',
  '................',
  'n..............n',
  'n..............n',
  '................',
  'n..............n',
  'n..............n',
  '................',
  'n..............n',
  'n..............n',
  '................',
  'n..............n',
  'n..............n',
  '................',
  '..nn..nn..nn..nn',
]

// --- 8×8 UI icons ---

const coin: SpriteGrid = [
  '..oooo..',
  '.oyyOOo.',
  'oyyOOOOo',
  'oyOOOOOo',
  'oOOOOOOo',
  'oOOOOOoo',
  '.oOOOoo.',
  '..oooo..',
]

const lock: SpriteGrid = [
  '..hhhh..',
  '.h....h.',
  '.h....h.',
  'hhhhhhhh',
  'hhhnnhhh',
  'hhhnnhhh',
  'hhhhhhhh',
  '.hhhhhh.',
]

const gear: SpriteGrid = [
  '.h.hh.h.',
  'hhhhhhhh',
  '.hhEEhh.',
  'hhEkkEhh',
  'hhEkkEhh',
  '.hhEEhh.',
  'hhhhhhhh',
  '.h.hh.h.',
]

const basket: SpriteGrid = [
  '..bbbb..',
  '.b....b.',
  'bbbbbbbb',
  'bDbDbDbb',
  'bbDbDbDb',
  'bDbDbDbb',
  '.bbbbbb.',
  '........',
]

const plus: SpriteGrid = [
  '........',
  '...ww...',
  '...ww...',
  '.wwwwww.',
  '.wwwwww.',
  '...ww...',
  '...ww...',
  '........',
]

const sparkle: SpriteGrid = [
  '........',
  '...y....',
  '..yWy...',
  '.yWWWy..',
  '..yWy...',
  '...y....',
  '........',
  '........',
]

// --- 16×16 upgrade icons ---

const giesskanne: SpriteGrid = [
  '................',
  '......nn........',
  '.....n..n.......',
  '.....n..n.......',
  '....nnnnnnnn....',
  '....nNNNNNNn..nn',
  '....nNhhNNNn.nn.',
  '....nNhhNNNnnn..',
  '....nNNNNNNn....',
  '....nNNNNNNn....',
  '....nnnnnnnn....',
  '..............c.',
  '..............c.',
  '................',
  '................',
  '................',
]

const duenger: SpriteGrid = [
  '................',
  '......bb........',
  '.....bDDb.......',
  '....bDDDDb......',
  '...bDDDDDDb.....',
  '..bDDDDDDDDb....',
  '..bDDDllDDDb....',
  '..bDDlflfDDb....',
  '..bDDDfFDDDb....',
  '..bDDDDfDDDb....',
  '..bDDDDDDDDb....',
  '...bDDDDDDb.....',
  '....bbbbbb......',
  '................',
  '................',
  '................',
]

const marktstand: SpriteGrid = [
  '................',
  '................',
  '.mwmwmwmwmwmw...',
  '.mwmwmwmwmwmw...',
  '.b..........b...',
  '.b..........b...',
  '.b..........b...',
  '.bDDDDDDDDDDb...',
  '.bDDDDDDDDDDb...',
  '.b..........b...',
  '.b..........b...',
  '.b..........b...',
  '................',
  '................',
  '................',
  '................',
]

/** Delivery note / quest board icon, 16×16. */
const scroll: SpriteGrid = [
  '................',
  '................',
  '....wwwwwwww....',
  '....wHHHHHHw....',
  '....wHnnnnHw....',
  '....wHHHHHHw....',
  '....wHnnnHHw....',
  '....wHHHHHHw....',
  '....wHnnnnHw....',
  '....wHHHHHHw....',
  '....wHnnHHHw....',
  '....wHHHHHHw....',
  '....wwwwwwww....',
  '................',
  '................',
  '................',
]

/** Crescent moon, 16×16. */
const moon: SpriteGrid = [
  '......wwww......',
  '....wwwwww......',
  '...wwwww........',
  '..wwwww.........',
  '..wwww..........',
  '.wwwww..........',
  '.wwww...........',
  '.wwww...........',
  '.wwww...........',
  '.wwwww..........',
  '..wwww..........',
  '..wwwww.........',
  '...wwwww........',
  '....wwwwww......',
  '......wwww......',
  '................',
]

/** Hedge silhouette tiles, 32×16, bottom half solid so layers can extend. */
const hedgeNear: SpriteGrid = [
  '....gg.........gggg.....gg......',
  '...gggg...gg..gggggg...gggg..gg.',
  '..gggggg.gggg.gGgggg..gggggg.ggg',
  '.ggggggggggggggggggg..ggggggggg.',
  'gggGgggggggggGggggggggggggggGggg',
  'gggggggGgggggggggggGgggggggggggg',
  'gggggggggggggggggggggggggggggggg',
  'gggggggggggggggggggggggggggggggg',
  'gggggggggggggggggggggggggggggggg',
  'gggggggggggggggggggggggggggggggg',
  'gggggggggggggggggggggggggggggggg',
  'gggggggggggggggggggggggggggggggg',
  'gggggggggggggggggggggggggggggggg',
  'gggggggggggggggggggggggggggggggg',
  'gggggggggggggggggggggggggggggggg',
  'gggggggggggggggggggggggggggggggg',
]

const hedgeFar: SpriteGrid = [
  '......KK.....KKKK........KK.....',
  '..KK.KKKK...KKKKKK..KK..KKKK....',
  '.KKKKKKKKK.KKKKKKKK.KKKKKKKKK.KK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
  'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
]

export const SPRITES: Record<string, SpriteGrid> = {
  'seedling': seedling,
  'basilikum-1': basilikum1,
  'basilikum-2': basilikum2,
  'basilikum-3': basilikum3,
  'minze-1': minze1,
  'minze-2': minze2,
  'minze-3': minze3,
  'lavendel-1': lavendel1,
  'lavendel-2': lavendel2,
  'lavendel-3': lavendel3,
  'karotte-1': karotte1,
  'karotte-2': karotte2,
  'karotte-3': karotte3,
  'tomate-1': tomate1,
  'tomate-2': tomate2,
  'tomate-3': tomate3,
  'kuerbis-1': kuerbis1,
  'kuerbis-2': kuerbis2,
  'kuerbis-3': kuerbis3,
  soil,
  'ghost-plot': ghostPlot,
  giesskanne,
  duenger,
  marktstand,
  scroll,
  coin,
  lock,
  gear,
  basket,
  plus,
  sparkle,
  moon,
  'hedge-near': hedgeNear,
  'hedge-far': hedgeFar,
}
